# Generated by Django 6.0.2 on 2026-02-13 02:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(max_length=50)),
                ('scheduled_time', models.DateTimeField()),
                ('description', models.TextField(help_text='Description of work needed')),
                ('location_address', models.TextField(help_text='Service location address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_processing', 'Payment Processing'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Service amount in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
