# Generated by Django 6.0.2 on 2026-02-13 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('municipalities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='citizen',
            field=models.ForeignKey(limit_choices_to={'role': 'citizen'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='municipality',
            field=models.ForeignKey(help_text='Municipality where service is provided (for local tracking)', on_delete=django.db.models.deletion.PROTECT, to='municipalities.municipality'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.PROTECT, related_name='provider_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['municipality', 'status', '-created_at'], name='bookings_municip_4f0b62_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status'], name='bookings_provide_f84a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['citizen', '-created_at'], name='bookings_citizen_2f228a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-completed_at'], name='bookings_complet_9d097b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-scheduled_time'], name='bookings_status_9a8ef2_idx'),
        ),
    ]
