# Generated by Django 6.0.2 on 2026-02-13 02:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='Phone number (10 digits starting with 98)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 98', regex='^98\\d{8}$')])),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('provider', 'Service Provider'), ('municipality_admin', 'Municipality Admin')], default='citizen', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='municipalities.municipality')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['phone'], name='users_phone_af6883_idx'), models.Index(fields=['municipality', 'role'], name='users_municip_0e4c75_idx')],
            },
        ),
    ]
