# Generated by Django 6.0.2 on 2026-02-13 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_categories', models.JSONField(default=list, help_text='List of skill category keys')),
                ('bio', models.TextField(blank=True, help_text='Provider description')),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('municipality_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('ctevt_status', models.CharField(choices=[('pending', 'Pending'), ('certified', 'Certified'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('ctevt_certificate_upload', models.FileField(blank=True, help_text='Upload CTEVT certificate (PDF/Image)', null=True, upload_to='certificates/')),
                ('ctevt_certificate_link', models.URLField(blank=True, help_text='Link to online CTEVT certificate', null=True)),
                ('citizenship_photo', models.ImageField(help_text='Citizenship card photo', upload_to='citizenship/')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('jobs_completed', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_profiles',
                'ordering': ['-avg_rating', '-jobs_completed'],
            },
        ),
    ]
