# Generated by Django 6.0.2 on 2026-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'db_table': 'municipalities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='municipalit_name_d1d450_idx'), models.Index(fields=['district'], name='municipalit_distric_9e7883_idx')],
            },
        ),
    ]
