# Generated by Django 6.0.2 on 2026-02-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
